import type { CargoClass, Zone } from "./types";
import type { Locale } from "./i18n/messages";

export type PortRegion =
  | "northern-europe"
  | "mediterranean"
  | "americas"
  | "middle-east"
  | "asia"
  | "africa"
  | "chokepoint";

export interface Port {
  id: string;
  name: string;
  country: string;
  flag: string;
  region: PortRegion;
  strategic?: boolean;
  nativeLocale: Locale;
  names: Partial<Record<Locale, string>>;
  countryNames: Partial<Record<Locale, string>>;
  center: [number, number];
  bbox: [number, number, number, number];
  zones: Zone[];
  cargoStrength: CargoClass[];
  blurb: string;
  blurbs?: Partial<Record<Locale, string>>;
}

const z = (
  id: string,
  name: string,
  kind: Zone["kind"],
  bbox: [number, number, number, number],
): Zone => ({ id, name, kind, bbox });

export const PORTS: Port[] = [
  {
    id: "rotterdam",
    name: "Rotterdam",
    country: "Netherlands",
    flag: "🇳🇱",
    region: "northern-europe",
    strategic: true,
    nativeLocale: "nl",
    names: {
      nl: "Rotterdam",
      en: "Rotterdam",
      fr: "Rotterdam",
      de: "Rotterdam",
      es: "Róterdam",
      ar: "روتردام",
      zh: "鹿特丹",
      ja: "ロッテルダム",
    },
    countryNames: {
      nl: "Nederland",
      en: "Netherlands",
      fr: "Pays-Bas",
      de: "Niederlande",
      es: "Países Bajos",
      ar: "هولندا",
      zh: "荷兰",
      ja: "オランダ",
    },
    center: [51.95, 4.1],
    bbox: [51.85, 3.5, 52.1, 4.55],
    cargoStrength: ["crude", "product", "container", "chemical", "lng"],
    blurb: "ARA hub n°1 · pétrochimie + conteneurs + LNG (Gate)",
    blurbs: {
      en: "ARA hub #1 · petrochem + containers + LNG (Gate)",
      nl: "ARA-hub nr. 1 · petrochemie + containers + LNG (Gate)",
      de: "ARA-Hub Nr. 1 · Petrochemie + Container + LNG (Gate)",
      es: "Hub ARA n.º 1 · petroquímica + contenedores + LNG (Gate)",
      ar: "محور ARA رقم 1 · بتروكيماويات + حاويات + LNG",
    },
    zones: [
      z("maas-north-anchorage", "Maas North Anchorage", "anchorage", [
        51.99, 3.65, 52.1, 3.95,
      ]),
      z("maas-south-anchorage", "Maas South Anchorage", "anchorage", [
        51.88, 3.6, 51.97, 3.95,
      ]),
      z("maasvlakte", "Maasvlakte", "berth", [51.94, 4.0, 52.0, 4.18]),
      z("europoort", "Europoort", "berth", [51.92, 4.05, 51.98, 4.22]),
      z("botlek", "Botlek", "berth", [51.86, 4.18, 51.92, 4.32]),
      z("waalhaven", "Waalhaven / City", "berth", [51.88, 4.32, 51.93, 4.55]),
      z("rotterdam-channel", "Nieuwe Waterweg", "channel", [
        51.93, 4.05, 51.96, 4.3,
      ]),
    ],
  },
  {
    id: "antwerp",
    name: "Antwerp",
    country: "Belgium",
    flag: "🇧🇪",
    region: "northern-europe",
    strategic: true,
    nativeLocale: "nl",
    names: {
      nl: "Antwerpen",
      en: "Antwerp",
      fr: "Anvers",
      de: "Antwerpen",
      es: "Amberes",
      ar: "أنتويرب",
      zh: "安特卫普",
      ja: "アントワープ",
    },
    countryNames: {
      nl: "België",
      en: "Belgium",
      fr: "Belgique",
      de: "Belgien",
      es: "Bélgica",
      ar: "بلجيكا",
      zh: "比利时",
      ja: "ベルギー",
    },
    center: [51.3, 4.25],
    bbox: [51.2, 3.9, 51.45, 4.4],
    cargoStrength: ["chemical", "product", "container", "general-cargo"],
    blurb: "ARA · chimie + raffinage + conteneurs · 2e port européen",
    blurbs: {
      en: "ARA · chemicals + refining + containers · #2 European port",
      nl: "ARA · chemie + raffinage + containers · 2e Europese haven",
      de: "ARA · Chemie + Raffinerie + Container · zweitgrößter europäischer Hafen",
      es: "ARA · química + refino + contenedores · 2.º puerto europeo",
      ar: "ARA · كيماويات + تكرير + حاويات · ثاني ميناء أوروبي",
    },
    zones: [
      z("antwerp-scheldt", "Scheldt approach", "approach", [
        51.2, 3.9, 51.3, 4.2,
      ]),
      z("antwerp-port", "Port interior", "berth", [51.25, 4.2, 51.45, 4.4]),
    ],
  },
  {
    id: "amsterdam",
    name: "Amsterdam",
    country: "Netherlands",
    flag: "🇳🇱",
    region: "northern-europe",
    strategic: true,
    nativeLocale: "nl",
    names: {
      nl: "Amsterdam",
      en: "Amsterdam",
      fr: "Amsterdam",
      de: "Amsterdam",
      es: "Ámsterdam",
      ar: "أمستردام",
      zh: "阿姆斯特丹",
      ja: "アムステルダム",
    },
    countryNames: {
      nl: "Nederland",
      en: "Netherlands",
      fr: "Pays-Bas",
      de: "Niederlande",
      es: "Países Bajos",
      ar: "هولندا",
      zh: "荷兰",
      ja: "オランダ",
    },
    center: [52.42, 4.78],
    bbox: [52.35, 4.5, 52.5, 4.95],
    cargoStrength: ["product", "dry-bulk", "container"],
    blurb: "ARA · stockage essence/gasoil + cacao + bulk · IJmuiden lock",
    blurbs: {
      en: "ARA · gasoline/diesel storage + cocoa + bulk · IJmuiden lock",
      nl: "ARA · benzine/dieselopslag + cacao + bulk · IJmuiden-sluis",
      de: "ARA · Benzin/Diesel-Lager + Kakao + Bulk · IJmuiden-Schleuse",
      es: "ARA · almacén gasolina/diésel + cacao + granel · esclusa de IJmuiden",
      ar: "ARA · تخزين بنزين/ديزل + كاكاو · هويس IJmuiden",
    },
    zones: [
      z("amsterdam-ijmuiden", "IJmuiden / North Sea", "approach", [
        52.4, 4.5, 52.5, 4.65,
      ]),
      z("amsterdam-port", "Noordzeekanaal + city", "berth", [
        52.35, 4.65, 52.5, 4.95,
      ]),
    ],
  },
  {
    id: "leHavre",
    name: "Le Havre",
    country: "France",
    flag: "🇫🇷",
    region: "northern-europe",
    strategic: true,
    nativeLocale: "fr",
    names: {
      fr: "Le Havre",
      en: "Le Havre",
      nl: "Le Havre",
      de: "Le Havre",
      es: "El Havre",
      ar: "لو هافر",
      zh: "勒阿弗尔",
      ja: "ル・アーヴル",
    },
    countryNames: {
      fr: "France",
      en: "France",
      nl: "Frankrijk",
      de: "Frankreich",
      es: "Francia",
      ar: "فرنسا",
      zh: "法国",
      ja: "フランス",
    },
    center: [49.48, 0.12],
    bbox: [49.4, -0.1, 49.6, 0.3],
    cargoStrength: ["container", "crude", "product", "ro-ro"],
    blurb:
      "1er port français pour conteneurs · raffinerie TotalEnergies · accès Manche",
    blurbs: {
      en: "France's #1 container port · TotalEnergies refinery · Channel access",
      fr: "1er port français pour conteneurs · raffinerie TotalEnergies · accès Manche",
      de: "Frankreichs Container-Hub Nr. 1 · TotalEnergies-Raffinerie · Zugang Ärmelkanal",
      es: "Puerto contenedor n.º 1 de Francia · refinería TotalEnergies · acceso Canal",
      nl: "Frankrijks #1 containerhaven · TotalEnergies-raffinaderij · Kanaal-toegang",
      ar: "أهم ميناء فرنسي للحاويات · مصفاة توتال · بوابة بحر المانش",
    },
    zones: [
      z("leHavre-approach", "Manche approach", "approach", [
        49.4, -0.1, 49.55, 0.1,
      ]),
      z("leHavre-port", "Port + Antifer", "berth", [49.45, 0.05, 49.6, 0.3]),
    ],
  },
  {
    id: "marseilleFos",
    name: "Marseille-Fos",
    country: "France",
    flag: "🇫🇷",
    region: "mediterranean",
    strategic: true,
    nativeLocale: "fr",
    names: {
      fr: "Marseille-Fos",
      en: "Marseille-Fos",
      nl: "Marseille-Fos",
      de: "Marseille-Fos",
      es: "Marsella-Fos",
      ar: "مرسيليا-فوس",
      zh: "马赛-福斯",
      ja: "マルセイユ＝フォス",
    },
    countryNames: {
      fr: "France",
      en: "France",
      nl: "Frankrijk",
      de: "Frankreich",
      es: "Francia",
      ar: "فرنسا",
      zh: "法国",
      ja: "フランス",
    },
    center: [43.4, 5.0],
    bbox: [43.2, 4.7, 43.5, 5.4],
    cargoStrength: ["crude", "product", "lng", "container", "chemical"],
    blurb:
      "1er port français en tonnage · LNG Fos-Cavaou + raffineries · gateway Méd",
    blurbs: {
      en: "France's largest port by tonnage · Fos-Cavaou LNG + refineries · Med gateway",
      fr: "1er port français en tonnage · LNG Fos-Cavaou + raffineries · gateway Méd",
      de: "Größter französischer Hafen nach Tonnage · LNG Fos-Cavaou · Mittelmeer-Gateway",
      es: "Mayor puerto francés por tonelaje · LNG Fos-Cavaou · puerta Mediterránea",
      nl: "Grootste Franse haven naar tonnage · LNG Fos-Cavaou · Middellandse Zee",
      ar: "أكبر ميناء فرنسي حمولة · LNG فوس · بوابة المتوسط",
    },
    zones: [
      z("fos-anchorage", "Fos anchorage", "anchorage", [
        43.2, 4.7, 43.4, 4.9,
      ]),
      z("fos-port", "Fos terminals", "berth", [43.35, 4.85, 43.45, 5.05]),
      z("marseille-port", "Marseille port", "berth", [
        43.3, 5.25, 43.4, 5.4,
      ]),
    ],
  },
  {
    id: "dunkerque",
    name: "Dunkerque",
    country: "France",
    flag: "🇫🇷",
    region: "northern-europe",
    strategic: true,
    nativeLocale: "fr",
    names: {
      fr: "Dunkerque",
      en: "Dunkirk",
      nl: "Duinkerke",
      de: "Dünkirchen",
      es: "Dunkerque",
      ar: "دونكيرك",
      zh: "敦刻尔克",
      ja: "ダンケルク",
    },
    countryNames: {
      fr: "France",
      en: "France",
      nl: "Frankrijk",
      de: "Frankreich",
      es: "Francia",
      ar: "فرنسا",
      zh: "法国",
      ja: "フランス",
    },
    center: [51.05, 2.3],
    bbox: [50.95, 2.1, 51.15, 2.5],
    cargoStrength: ["dry-bulk", "lng", "product", "ro-ro"],
    blurb:
      "Vrac (charbon, minerai) · LNG Dunkerque · 3e port français en tonnage",
    blurbs: {
      en: "Bulk (coal, ore) · Dunkerque LNG · France's #3 by tonnage",
      fr: "Vrac (charbon, minerai) · LNG Dunkerque · 3e port français en tonnage",
      de: "Bulk (Kohle, Erz) · Dünkirchen LNG · 3. französischer Hafen",
      es: "Granel (carbón, mineral) · LNG Dunkerque · 3.º francés en tonelaje",
      nl: "Bulk (kolen, erts) · Duinkerke LNG · 3e Franse haven",
      ar: "سائبة (فحم، خام) · LNG · ثالث ميناء فرنسي",
    },
    zones: [
      z("dunkerque-approach", "Dunkerque approach", "approach", [
        50.95, 2.1, 51.1, 2.25,
      ]),
      z("dunkerque-port", "Port Ouest + Est", "berth", [
        51.0, 2.2, 51.15, 2.5,
      ]),
    ],
  },
  {
    id: "stNazaire",
    name: "Saint-Nazaire / Montoir",
    country: "France",
    flag: "🇫🇷",
    region: "northern-europe",
    strategic: true,
    nativeLocale: "fr",
    names: {
      fr: "Saint-Nazaire / Montoir",
      en: "Saint-Nazaire / Montoir",
      nl: "Saint-Nazaire / Montoir",
      de: "Saint-Nazaire / Montoir",
      es: "Saint-Nazaire / Montoir",
      ar: "سان نازير / مونتوار",
      zh: "圣纳泽尔 / 蒙图瓦",
      ja: "サン＝ナゼール / モントワール",
    },
    countryNames: {
      fr: "France",
      en: "France",
      nl: "Frankrijk",
      de: "Frankreich",
      es: "Francia",
      ar: "فرنسا",
      zh: "法国",
      ja: "フランス",
    },
    center: [47.27, -2.18],
    bbox: [47.15, -2.45, 47.35, -2.0],
    cargoStrength: ["lng", "product", "general-cargo"],
    blurb:
      "Terminal méthanier Montoir · estuaire Loire · accès Atlantique",
    blurbs: {
      en: "Montoir LNG terminal · Loire estuary · Atlantic gateway",
      fr: "Terminal méthanier Montoir · estuaire Loire · accès Atlantique",
      de: "LNG-Terminal Montoir · Loire-Mündung · Atlantik-Tor",
      es: "Terminal LNG Montoir · estuario del Loira · acceso Atlántico",
      nl: "LNG-terminal Montoir · Loire-mond · Atlantische toegang",
      ar: "محطة LNG مونتوار · مصب نهر اللوار · بوابة المحيط الأطلسي",
    },
    zones: [
      z("stNazaire-approach", "Loire estuary", "approach", [
        47.15, -2.45, 47.3, -2.2,
      ]),
      z("stNazaire-port", "Saint-Nazaire + Montoir", "berth", [
        47.25, -2.2, 47.35, -2.0,
      ]),
    ],
  },
  {
    id: "hamburg",
    name: "Hamburg",
    country: "Germany",
    flag: "🇩🇪",
    region: "northern-europe",
    strategic: true,
    nativeLocale: "de",
    names: {
      de: "Hamburg",
      en: "Hamburg",
      fr: "Hambourg",
      nl: "Hamburg",
      es: "Hamburgo",
      ar: "هامبورغ",
      zh: "汉堡",
      ja: "ハンブルク",
    },
    countryNames: {
      de: "Deutschland",
      en: "Germany",
      fr: "Allemagne",
      nl: "Duitsland",
      es: "Alemania",
      ar: "ألمانيا",
      zh: "德国",
      ja: "ドイツ",
    },
    center: [53.55, 9.95],
    bbox: [53.45, 9.4, 53.65, 10.2],
    cargoStrength: ["container", "dry-bulk", "general-cargo"],
    blurb: "North Europe container hub · vrac · accès Elbe",
    blurbs: {
      en: "North Europe container hub · bulk · Elbe access",
      de: "Nordeuropäischer Container-Hub · Bulk · Elbzugang",
      nl: "Containerhub Noord-Europa · bulk · Elbe-toegang",
      es: "Hub de contenedores Norte de Europa · granel · acceso Elba",
      ar: "محور حاويات شمال أوروبا · سائبة · عبر نهر إلبه",
    },
    zones: [
      z("hamburg-elbe", "Elbe approach", "approach", [
        53.45, 9.4, 53.6, 9.85,
      ]),
      z("hamburg-port", "Hamburg port", "berth", [53.5, 9.85, 53.65, 10.1]),
    ],
  },
  {
    id: "algeciras",
    name: "Algeciras",
    country: "Spain",
    flag: "🇪🇸",
    region: "mediterranean",
    strategic: true,
    nativeLocale: "es",
    names: {
      es: "Algeciras",
      en: "Algeciras",
      fr: "Algésiras",
      nl: "Algeciras",
      de: "Algeciras",
      ar: "الجزيرة الخضراء",
      zh: "阿尔赫西拉斯",
      ja: "アルヘシラス",
    },
    countryNames: {
      es: "España",
      en: "Spain",
      fr: "Espagne",
      nl: "Spanje",
      de: "Spanien",
      ar: "إسبانيا",
      zh: "西班牙",
      ja: "スペイン",
    },
    center: [36.12, -5.42],
    bbox: [35.95, -5.55, 36.2, -5.3],
    cargoStrength: ["container", "product", "crude"],
    blurb: "Méd · transshipment conteneurs + soutage majeur · gateway Gibraltar",
    blurbs: {
      en: "Med · container transshipment + major bunkering · Gibraltar gateway",
      es: "Mediterráneo · trasbordo de contenedores + bunkering · puerta de Gibraltar",
      de: "Mittelmeer · Container-Umschlag + Bunkering · Gibraltar-Gateway",
      nl: "Middellandse Zee · containertransshipment + bunkering · poort Gibraltar",
      ar: "المتوسط · تحويل حاويات + تزويد بالوقود · بوابة جبل طارق",
    },
    zones: [
      z("algeciras-bay", "Bay of Gibraltar", "anchorage", [
        35.95, -5.5, 36.15, -5.35,
      ]),
      z("algeciras-port", "Algeciras port", "berth", [
        36.1, -5.45, 36.2, -5.35,
      ]),
    ],
  },
  {
    id: "fujairah",
    name: "Fujairah",
    country: "UAE",
    flag: "🇦🇪",
    region: "middle-east",
    strategic: true,
    nativeLocale: "ar",
    names: {
      ar: "الفجيرة",
      en: "Fujairah",
      fr: "Foujaïrah",
      nl: "Fujairah",
      de: "Fudschaira",
      es: "Fujaira",
      zh: "富查伊拉",
      ja: "フジャイラ",
    },
    countryNames: {
      ar: "الإمارات",
      en: "UAE",
      fr: "Émirats arabes unis",
      nl: "Verenigde Arabische Emiraten",
      de: "Vereinigte Arabische Emirate",
      es: "Emiratos Árabes Unidos",
      zh: "阿联酋",
      ja: "アラブ首長国連邦",
    },
    center: [25.2, 56.4],
    bbox: [25.05, 56.3, 25.4, 56.55],
    cargoStrength: ["crude", "product", "lpg"],
    blurb: "Soutage mondial #2 · gateway Hormuz · stockage produits raffinés",
    blurbs: {
      en: "World #2 bunkering · Hormuz gateway · refined products storage",
      ar: "ثاني محور تزويد بالوقود عالمياً · بوابة هرمز · تخزين المنتجات المكررة",
      fr: "Soutage mondial n°2 · gateway Hormuz · stockage produits raffinés",
      de: "Bunkering-Standort Nr. 2 weltweit · Hormus-Gateway · Lagerung Raffinerieprodukte",
      es: "Bunkering mundial n.º 2 · puerta de Ormuz · almacenamiento de productos refinados",
      nl: "Wereld nr. 2 bunkering · Hormuz-poort · opslag geraffineerde producten",
    },
    zones: [
      z("fujairah-anchorage", "Fujairah anchorage", "anchorage", [
        25.05, 56.4, 25.4, 56.55,
      ]),
      z("fujairah-port", "Fujairah port", "berth", [
        25.13, 56.32, 25.22, 56.4,
      ]),
    ],
  },
  {
    id: "singapore",
    name: "Singapore",
    country: "Singapore",
    flag: "🇸🇬",
    region: "asia",
    strategic: true,
    nativeLocale: "en",
    names: {
      en: "Singapore",
      fr: "Singapour",
      nl: "Singapore",
      de: "Singapur",
      es: "Singapur",
      ar: "سنغافورة",
      zh: "新加坡",
      ja: "シンガポール",
    },
    countryNames: {
      en: "Singapore",
      fr: "Singapour",
      nl: "Singapore",
      de: "Singapur",
      es: "Singapur",
      ar: "سنغافورة",
      zh: "新加坡",
      ja: "シンガポール",
    },
    center: [1.25, 103.85],
    bbox: [1.1, 103.55, 1.4, 104.1],
    cargoStrength: [
      "container",
      "crude",
      "product",
      "chemical",
      "lng",
      "lpg",
    ],
    blurb: "Soutage mondial #1 · transit Asie · raffinage Jurong",
    blurbs: {
      en: "World #1 bunkering · Asia transit · Jurong refining",
      fr: "Soutage mondial n°1 · transit Asie · raffinage Jurong",
      de: "Bunkering Nr. 1 weltweit · Asien-Transit · Raffinerie Jurong",
      es: "Bunkering mundial n.º 1 · tránsito Asia · refino Jurong",
      nl: "Wereld nr. 1 bunkering · Azië-transit · raffinage Jurong",
      ar: "أول محور تزويد بالوقود عالمياً · ممر آسيا · مصافي جورونغ",
    },
    zones: [
      z("singapore-east", "Eastern anchorages", "anchorage", [
        1.1, 103.85, 1.3, 104.1,
      ]),
      z("singapore-west", "Western anchorages", "anchorage", [
        1.1, 103.55, 1.3, 103.75,
      ]),
      z("singapore-port", "Port + Jurong", "berth", [
        1.2, 103.6, 1.32, 103.9,
      ]),
    ],
  },
  {
    id: "houston",
    name: "Houston",
    country: "USA",
    flag: "🇺🇸",
    region: "americas",
    strategic: true,
    nativeLocale: "en",
    names: {
      en: "Houston",
      fr: "Houston",
      nl: "Houston",
      de: "Houston",
      es: "Houston",
      ar: "هيوستن",
      zh: "休斯顿",
      ja: "ヒューストン",
    },
    countryNames: {
      en: "USA",
      fr: "États-Unis",
      nl: "Verenigde Staten",
      de: "USA",
      es: "EE. UU.",
      ar: "الولايات المتحدة",
      zh: "美国",
      ja: "アメリカ",
    },
    center: [29.7, -95.0],
    bbox: [29.5, -95.3, 29.9, -94.7],
    cargoStrength: ["crude", "product", "chemical", "lng"],
    blurb: "US Gulf gateway · pétrochimie + LNG (Freeport via canal)",
    blurbs: {
      en: "US Gulf gateway · petrochem + LNG (Freeport via channel)",
      fr: "Porte du Golfe US · pétrochimie + LNG (Freeport via canal)",
      de: "Tor zum Golf von Mexiko · Petrochemie + LNG (Freeport)",
      es: "Puerta del Golfo de EE. UU. · petroquímica + LNG (Freeport)",
      nl: "Poort tot de Amerikaanse Golf · petrochemie + LNG (Freeport)",
      ar: "بوابة خليج الولايات المتحدة · بتروكيماويات + LNG",
    },
    zones: [
      z("houston-channel", "Houston Ship Channel", "channel", [
        29.6, -95.2, 29.8, -94.85,
      ]),
      z("galveston-bay", "Galveston Bay anchorage", "anchorage", [
        29.5, -94.95, 29.7, -94.75,
      ]),
      z("houston-port", "Houston port", "berth", [29.7, -95.3, 29.85, -95.05]),
    ],
  },
  {
    id: "sabine",
    name: "Sabine Pass",
    country: "USA",
    flag: "🇺🇸",
    region: "americas",
    strategic: true,
    nativeLocale: "en",
    names: {
      en: "Sabine Pass",
      fr: "Sabine Pass",
      nl: "Sabine Pass",
      de: "Sabine Pass",
      es: "Sabine Pass",
      ar: "سابين باس",
      zh: "萨宾通道",
      ja: "サビーン・パス",
    },
    countryNames: {
      en: "USA",
      fr: "États-Unis",
      nl: "Verenigde Staten",
      de: "USA",
      es: "EE. UU.",
      ar: "الولايات المتحدة",
      zh: "美国",
      ja: "アメリカ",
    },
    center: [29.7, -93.85],
    bbox: [29.5, -94.1, 29.9, -93.7],
    cargoStrength: ["lng", "crude", "product"],
    blurb: "US LNG export majeur · terminal Cheniere",
    blurbs: {
      en: "Major US LNG export · Cheniere terminal",
      fr: "Export LNG US majeur · terminal Cheniere",
      de: "Wichtiger US-LNG-Export · Cheniere-Terminal",
      es: "Exportación principal de LNG en EE. UU. · terminal Cheniere",
      nl: "Belangrijke Amerikaanse LNG-export · Cheniere-terminal",
      ar: "تصدير LNG رئيسي · محطة شينير",
    },
    zones: [
      z("sabine-offshore", "Sabine offshore", "anchorage", [
        29.5, -94.05, 29.7, -93.7,
      ]),
      z("sabine-terminal", "Sabine LNG terminal", "berth", [
        29.7, -94.05, 29.85, -93.85,
      ]),
    ],
  },
  {
    id: "hormuz",
    name: "Strait of Hormuz",
    country: "Chokepoint",
    flag: "⚓",
    region: "chokepoint",
    strategic: true,
    nativeLocale: "ar",
    names: {
      ar: "مضيق هرمز",
      en: "Strait of Hormuz",
      fr: "Détroit d'Ormuz",
      nl: "Straat van Hormuz",
      de: "Straße von Hormus",
      es: "Estrecho de Ormuz",
      zh: "霍尔木兹海峡",
      ja: "ホルムズ海峡",
    },
    countryNames: {
      ar: "ممر استراتيجي",
      en: "Strategic chokepoint",
      fr: "Chokepoint stratégique",
      nl: "Strategisch knelpunt",
      de: "Strategischer Engpass",
      es: "Punto estratégico",
      zh: "战略要冲",
      ja: "戦略的要衝",
    },
    center: [26.5, 56.5],
    bbox: [25.0, 55.0, 27.5, 57.5],
    cargoStrength: ["crude", "lng", "lpg", "product"],
    blurb:
      "Chokepoint stratégique · ~20-30% du pétrole mondial transite par là · sortie golfe Persique vers golfe d'Oman",
    blurbs: {
      en: "Strategic chokepoint · ~20-30% of global oil transits here · Persian Gulf to Gulf of Oman",
      ar: "ممر استراتيجي · 20-30٪ من النفط العالمي يمر من هنا · من الخليج العربي إلى خليج عمان",
      fr: "Chokepoint stratégique · 20-30% du pétrole mondial · sortie golfe Persique vers golfe d'Oman",
      de: "Strategischer Engpass · 20-30% des weltweiten Öls · Persischer Golf zum Golf von Oman",
      es: "Punto estratégico · 20-30% del petróleo mundial · Golfo Pérsico al Golfo de Omán",
      nl: "Strategisch knelpunt · 20-30% van wereldolie · Perzische Golf naar Golf van Oman",
    },
    zones: [
      z("hormuz-narrow", "Narrow passage", "channel", [
        26.3, 56.0, 26.8, 56.7,
      ]),
      z("hormuz-east", "Gulf of Oman approach", "approach", [
        25.0, 56.5, 26.3, 57.5,
      ]),
      z("hormuz-west", "Persian Gulf approach", "approach", [
        25.0, 55.0, 26.5, 56.0,
      ]),
    ],
  },
  {
    id: "rasLaffan",
    name: "Ras Laffan",
    country: "Qatar",
    flag: "🇶🇦",
    region: "middle-east",
    strategic: true,
    nativeLocale: "ar",
    names: {
      ar: "راس لفان",
      en: "Ras Laffan",
      fr: "Ras Laffan",
      nl: "Ras Laffan",
      de: "Ras Laffan",
      es: "Ras Laffan",
      zh: "拉斯拉凡",
      ja: "ラス・ラファン",
    },
    countryNames: {
      ar: "قطر",
      en: "Qatar",
      fr: "Qatar",
      nl: "Qatar",
      de: "Katar",
      es: "Catar",
      zh: "卡塔尔",
      ja: "カタール",
    },
    center: [25.95, 51.6],
    bbox: [25.85, 51.5, 26.05, 51.8],
    cargoStrength: ["lng", "lpg", "crude"],
    blurb: "Qatar LNG export · 1er port LNG mondial historique",
    blurbs: {
      ar: "تصدير قطر للغاز · أول ميناء LNG عالمي تاريخياً",
      en: "Qatar LNG export · historic #1 LNG port globally",
      fr: "Export LNG du Qatar · 1er port LNG mondial historique",
      de: "Katar LNG-Export · historisch weltgrößter LNG-Hafen",
      es: "Exportación LNG Qatar · histórico n.º 1 LNG mundial",
      nl: "Qatar LNG-export · historisch nr. 1 LNG-haven wereldwijd",
    },
    zones: [
      z("rasLaffan-anchorage", "Offshore anchorage", "anchorage", [
        25.85, 51.65, 26.05, 51.8,
      ]),
      z("rasLaffan-terminal", "LNG terminal", "berth", [
        25.9, 51.5, 26.0, 51.65,
      ]),
    ],
  },

  // === Northern Europe (extended) ===
  {
    id: "bremerhaven",
    name: "Bremerhaven",
    country: "Germany",
    flag: "🇩🇪",
    region: "northern-europe",
    nativeLocale: "de",
    names: { de: "Bremerhaven", en: "Bremerhaven", fr: "Bremerhaven" },
    countryNames: { de: "Deutschland", en: "Germany", fr: "Allemagne" },
    center: [53.55, 8.58],
    bbox: [53.45, 8.4, 53.7, 8.7],
    cargoStrength: ["container", "ro-ro"],
    blurb: "Container hub allemand · véhicules · accès Weser",
    blurbs: { en: "German container hub · cars · Weser access" },
    zones: [
      z("brv-approach", "Weser approach", "approach", [53.45, 8.4, 53.55, 8.55]),
      z("brv-port", "Bremerhaven port", "berth", [53.5, 8.5, 53.7, 8.7]),
    ],
  },
  {
    id: "felixstowe",
    name: "Felixstowe",
    country: "United Kingdom",
    flag: "🇬🇧",
    region: "northern-europe",
    nativeLocale: "en",
    names: { en: "Felixstowe", fr: "Felixstowe" },
    countryNames: { en: "United Kingdom", fr: "Royaume-Uni" },
    center: [51.95, 1.31],
    bbox: [51.85, 1.15, 52.05, 1.5],
    cargoStrength: ["container"],
    blurb: "1er port conteneurs UK · accès Mer du Nord",
    blurbs: { en: "UK's #1 container port · North Sea access" },
    zones: [
      z("fxt-approach", "Approach", "approach", [51.85, 1.15, 51.95, 1.3]),
      z("fxt-port", "Felixstowe port", "berth", [51.93, 1.3, 52.0, 1.45]),
    ],
  },
  {
    id: "southampton",
    name: "Southampton",
    country: "United Kingdom",
    flag: "🇬🇧",
    region: "northern-europe",
    nativeLocale: "en",
    names: { en: "Southampton", fr: "Southampton" },
    countryNames: { en: "United Kingdom", fr: "Royaume-Uni" },
    center: [50.9, -1.4],
    bbox: [50.7, -1.6, 51.0, -1.2],
    cargoStrength: ["container", "ro-ro", "passenger"],
    blurb: "Container + croisière + véhicules · Solent",
    blurbs: { en: "Container + cruise + cars · Solent" },
    zones: [
      z("sou-solent", "Solent", "approach", [50.7, -1.55, 50.85, -1.25]),
      z("sou-port", "Southampton docks", "berth", [50.88, -1.45, 51.0, -1.3]),
    ],
  },
  {
    id: "milfordHaven",
    name: "Milford Haven",
    country: "United Kingdom",
    flag: "🇬🇧",
    region: "northern-europe",
    nativeLocale: "en",
    names: { en: "Milford Haven", fr: "Milford Haven" },
    countryNames: { en: "United Kingdom", fr: "Royaume-Uni" },
    center: [51.7, -5.0],
    bbox: [51.6, -5.2, 51.8, -4.8],
    cargoStrength: ["lng", "crude", "product"],
    blurb: "Pétrole + LNG UK · raffinerie Pembroke",
    blurbs: { en: "UK oil + LNG · Pembroke refinery" },
    zones: [
      z("mlf-approach", "Haven approach", "approach", [51.6, -5.2, 51.7, -4.95]),
      z("mlf-port", "Milford terminals", "berth", [51.68, -5.05, 51.8, -4.85]),
    ],
  },
  {
    id: "gdansk",
    name: "Gdansk",
    country: "Poland",
    flag: "🇵🇱",
    region: "northern-europe",
    nativeLocale: "en",
    names: { en: "Gdansk", fr: "Gdansk" },
    countryNames: { en: "Poland", fr: "Pologne" },
    center: [54.5, 18.7],
    bbox: [54.35, 18.4, 54.7, 18.95],
    cargoStrength: ["container", "crude", "product"],
    blurb: "Hub Baltique · DCT container + Naftoport pétrole",
    blurbs: { en: "Baltic hub · DCT container + Naftoport oil" },
    zones: [
      z("gdn-approach", "Bay of Gdansk", "approach", [54.4, 18.5, 54.55, 18.85]),
      z("gdn-port", "Gdansk terminals", "berth", [54.4, 18.6, 54.55, 18.95]),
    ],
  },

  // === Mediterranean (extended) ===
  {
    id: "genoa",
    name: "Genoa",
    country: "Italy",
    flag: "🇮🇹",
    region: "mediterranean",
    nativeLocale: "en",
    names: { en: "Genoa", fr: "Gênes", de: "Genua", es: "Génova" },
    countryNames: { en: "Italy", fr: "Italie", de: "Italien", es: "Italia" },
    center: [44.4, 8.95],
    bbox: [44.3, 8.8, 44.5, 9.1],
    cargoStrength: ["container", "ro-ro", "product"],
    blurb: "1er port italien · porte d'entrée nord-Italie",
    blurbs: { en: "Italy's #1 port · North Italy gateway" },
    zones: [
      z("gen-approach", "Ligurian approach", "approach", [44.3, 8.8, 44.4, 9.1]),
      z("gen-port", "Genoa port", "berth", [44.4, 8.85, 44.5, 9.05]),
    ],
  },
  {
    id: "trieste",
    name: "Trieste",
    country: "Italy",
    flag: "🇮🇹",
    region: "mediterranean",
    nativeLocale: "en",
    names: { en: "Trieste", fr: "Trieste", de: "Triest" },
    countryNames: { en: "Italy", fr: "Italie", de: "Italien" },
    center: [45.65, 13.75],
    bbox: [45.55, 13.55, 45.8, 13.95],
    cargoStrength: ["crude", "container", "ro-ro"],
    blurb: "Adriatique · TAL pipeline pétrole · porte centre-Europe",
    blurbs: {
      en: "Adriatic · TAL oil pipeline · Central Europe gateway",
    },
    zones: [
      z("trs-approach", "Adriatic approach", "approach", [45.55, 13.55, 45.65, 13.85]),
      z("trs-port", "Trieste port", "berth", [45.62, 13.7, 45.75, 13.95]),
    ],
  },
  {
    id: "piraeus",
    name: "Piraeus",
    country: "Greece",
    flag: "🇬🇷",
    region: "mediterranean",
    nativeLocale: "en",
    names: { en: "Piraeus", fr: "Le Pirée", de: "Piräus" },
    countryNames: { en: "Greece", fr: "Grèce", de: "Griechenland" },
    center: [37.94, 23.65],
    bbox: [37.85, 23.5, 38.05, 23.8],
    cargoStrength: ["container", "passenger", "ro-ro"],
    blurb: "Méd Est · COSCO operator · gateway Balkans",
    blurbs: { en: "East Med · COSCO operator · Balkans gateway" },
    zones: [
      z("pir-approach", "Saronic approach", "approach", [37.85, 23.5, 37.95, 23.75]),
      z("pir-port", "Piraeus terminals", "berth", [37.93, 23.55, 38.05, 23.75]),
    ],
  },
  {
    id: "valencia",
    name: "Valencia",
    country: "Spain",
    flag: "🇪🇸",
    region: "mediterranean",
    nativeLocale: "es",
    names: { es: "Valencia", en: "Valencia", fr: "Valence" },
    countryNames: { es: "España", en: "Spain", fr: "Espagne" },
    center: [39.45, -0.32],
    bbox: [39.35, -0.45, 39.55, -0.15],
    cargoStrength: ["container", "ro-ro"],
    blurb: "1er port conteneurs Méd ouest · transshipment",
    blurbs: { en: "West Med #1 container · transshipment" },
    zones: [
      z("val-approach", "Approach", "approach", [39.35, -0.45, 39.45, -0.2]),
      z("val-port", "Valencia port", "berth", [39.42, -0.35, 39.55, -0.2]),
    ],
  },
  {
    id: "tangerMed",
    name: "Tanger Med",
    country: "Morocco",
    flag: "🇲🇦",
    region: "mediterranean",
    nativeLocale: "ar",
    names: { ar: "ميناء طنجة المتوسط", en: "Tanger Med", fr: "Tanger Med" },
    countryNames: { ar: "المغرب", en: "Morocco", fr: "Maroc" },
    center: [35.88, -5.5],
    bbox: [35.8, -5.7, 36.0, -5.3],
    cargoStrength: ["container", "ro-ro"],
    blurb: "Hub conteneurs Afrique du nord · porte détroit Gibraltar",
    blurbs: {
      en: "North Africa container hub · Gibraltar Strait gateway",
    },
    zones: [
      z("tng-approach", "Strait approach", "approach", [35.8, -5.7, 35.95, -5.45]),
      z("tng-port", "Tanger Med port", "berth", [35.88, -5.55, 36.0, -5.3]),
    ],
  },

  // === Americas (extended) ===
  {
    id: "losAngeles",
    name: "Los Angeles",
    country: "USA",
    flag: "🇺🇸",
    region: "americas",
    nativeLocale: "en",
    names: { en: "Los Angeles", fr: "Los Angeles", es: "Los Ángeles" },
    countryNames: { en: "USA", fr: "États-Unis", es: "EE. UU." },
    center: [33.73, -118.27],
    bbox: [33.6, -118.45, 33.85, -118.1],
    cargoStrength: ["container", "ro-ro"],
    blurb: "1er port conteneurs USA · Asie-Amérique gateway",
    blurbs: { en: "USA #1 container port · Asia-USA gateway" },
    zones: [
      z("lax-approach", "San Pedro approach", "approach", [
        33.6, -118.45, 33.73, -118.2,
      ]),
      z("lax-port", "LA port", "berth", [33.7, -118.3, 33.85, -118.15]),
    ],
  },
  {
    id: "longBeach",
    name: "Long Beach",
    country: "USA",
    flag: "🇺🇸",
    region: "americas",
    nativeLocale: "en",
    names: { en: "Long Beach", fr: "Long Beach" },
    countryNames: { en: "USA", fr: "États-Unis" },
    center: [33.76, -118.2],
    bbox: [33.65, -118.35, 33.85, -118.05],
    cargoStrength: ["container", "crude"],
    blurb: "Conteneurs + pétrole · second port USA",
    blurbs: { en: "Container + oil · USA #2" },
    zones: [
      z("lgb-approach", "Approach", "approach", [33.65, -118.35, 33.76, -118.15]),
      z("lgb-port", "Long Beach port", "berth", [33.74, -118.25, 33.85, -118.05]),
    ],
  },
  {
    id: "newYorkNJ",
    name: "New York / Newark",
    country: "USA",
    flag: "🇺🇸",
    region: "americas",
    nativeLocale: "en",
    names: { en: "New York / Newark", fr: "New York / Newark" },
    countryNames: { en: "USA", fr: "États-Unis" },
    center: [40.66, -74.06],
    bbox: [40.5, -74.25, 40.8, -73.85],
    cargoStrength: ["container", "ro-ro"],
    blurb: "1er port côte est USA · NY/NJ Bayonne",
    blurbs: { en: "USA East Coast #1 · NY/NJ Bayonne" },
    zones: [
      z("nyc-approach", "NY harbor approach", "approach", [
        40.5, -74.15, 40.65, -73.85,
      ]),
      z("nyc-port", "NY/NJ terminals", "berth", [40.65, -74.25, 40.8, -74.0]),
    ],
  },
  {
    id: "savannah",
    name: "Savannah",
    country: "USA",
    flag: "🇺🇸",
    region: "americas",
    nativeLocale: "en",
    names: { en: "Savannah", fr: "Savannah" },
    countryNames: { en: "USA", fr: "États-Unis" },
    center: [32.13, -81.13],
    bbox: [32.0, -81.3, 32.3, -80.9],
    cargoStrength: ["container"],
    blurb: "Container hub côte est sud · Garden City terminal",
    blurbs: { en: "South East Coast container hub · Garden City" },
    zones: [
      z("sav-approach", "Tybee approach", "approach", [32.0, -81.0, 32.15, -80.9]),
      z("sav-port", "Savannah port", "berth", [32.1, -81.25, 32.25, -81.05]),
    ],
  },
  {
    id: "corpusChristi",
    name: "Corpus Christi",
    country: "USA",
    flag: "🇺🇸",
    region: "americas",
    nativeLocale: "en",
    names: { en: "Corpus Christi", fr: "Corpus Christi" },
    countryNames: { en: "USA", fr: "États-Unis" },
    center: [27.82, -97.4],
    bbox: [27.7, -97.55, 28.0, -97.05],
    cargoStrength: ["crude", "lng", "product"],
    blurb: "1er export crude USA · Permian → tankers",
    blurbs: { en: "USA #1 crude export · Permian → tankers" },
    zones: [
      z("cc-approach", "Gulf approach", "approach", [27.7, -97.3, 27.85, -97.05]),
      z("cc-port", "Corpus terminals", "berth", [27.8, -97.5, 27.95, -97.3]),
    ],
  },
  {
    id: "newOrleans",
    name: "New Orleans / Lower Mississippi",
    country: "USA",
    flag: "🇺🇸",
    region: "americas",
    nativeLocale: "en",
    names: {
      en: "New Orleans / Lower Mississippi",
      fr: "Nouvelle-Orléans / Mississippi",
    },
    countryNames: { en: "USA", fr: "États-Unis" },
    center: [29.9, -90.05],
    bbox: [29.0, -90.6, 30.1, -89.0],
    cargoStrength: ["dry-bulk", "crude", "product", "general-cargo"],
    blurb: "Mississippi delta · grains + pétrole · 1er port USA tonnage",
    blurbs: {
      en: "Mississippi delta · grains + oil · USA #1 by tonnage",
    },
    zones: [
      z("no-approach", "SW Pass approach", "approach", [29.0, -89.7, 29.5, -89.0]),
      z("no-port", "NOLA terminals", "berth", [29.7, -90.6, 30.1, -89.7]),
    ],
  },
  {
    id: "santos",
    name: "Santos",
    country: "Brazil",
    flag: "🇧🇷",
    region: "americas",
    nativeLocale: "es",
    names: { es: "Santos", en: "Santos", fr: "Santos" },
    countryNames: { es: "Brasil", en: "Brazil", fr: "Brésil" },
    center: [-23.97, -46.32],
    bbox: [-24.1, -46.5, -23.85, -46.15],
    cargoStrength: ["container", "dry-bulk", "product"],
    blurb: "1er port LATAM · soja + sucre + conteneurs",
    blurbs: { en: "LATAM #1 port · soy + sugar + containers" },
    zones: [
      z("san-approach", "Santos approach", "approach", [-24.1, -46.45, -24.0, -46.2]),
      z("san-port", "Santos terminals", "berth", [-23.97, -46.4, -23.85, -46.2]),
    ],
  },
  {
    id: "cartagena",
    name: "Cartagena",
    country: "Colombia",
    flag: "🇨🇴",
    region: "americas",
    nativeLocale: "es",
    names: { es: "Cartagena", en: "Cartagena", fr: "Carthagène" },
    countryNames: { es: "Colombia", en: "Colombia", fr: "Colombie" },
    center: [10.4, -75.55],
    bbox: [10.25, -75.7, 10.55, -75.4],
    cargoStrength: ["container", "crude"],
    blurb: "Hub conteneurs Caraïbes · transshipment Panama",
    blurbs: { en: "Caribbean container hub · Panama transshipment" },
    zones: [
      z("car-approach", "Bay approach", "approach", [10.25, -75.65, 10.4, -75.45]),
      z("car-port", "Cartagena port", "berth", [10.35, -75.6, 10.55, -75.45]),
    ],
  },

  // === Middle East (extended) ===
  {
    id: "jebelAli",
    name: "Jebel Ali",
    country: "UAE",
    flag: "🇦🇪",
    region: "middle-east",
    nativeLocale: "ar",
    names: { ar: "جبل علي", en: "Jebel Ali", fr: "Jebel Ali" },
    countryNames: { ar: "الإمارات", en: "UAE", fr: "Émirats arabes unis" },
    center: [25.0, 55.07],
    bbox: [24.85, 54.85, 25.15, 55.25],
    cargoStrength: ["container", "general-cargo"],
    blurb: "1er port conteneurs Moyen-Orient · DP World hub",
    blurbs: { en: "Middle East #1 container · DP World hub" },
    zones: [
      z("jea-approach", "Approach", "approach", [24.85, 54.85, 25.0, 55.15]),
      z("jea-port", "Jebel Ali port", "berth", [24.95, 55.0, 25.15, 55.2]),
    ],
  },
  {
    id: "jeddah",
    name: "Jeddah",
    country: "Saudi Arabia",
    flag: "🇸🇦",
    region: "middle-east",
    nativeLocale: "ar",
    names: { ar: "جدة", en: "Jeddah", fr: "Djeddah" },
    countryNames: { ar: "السعودية", en: "Saudi Arabia", fr: "Arabie Saoudite" },
    center: [21.5, 39.18],
    bbox: [21.3, 38.95, 21.7, 39.4],
    cargoStrength: ["container", "general-cargo"],
    blurb: "Hub Mer Rouge · Saudi Arabia · pèlerinage + conteneurs",
    blurbs: { en: "Red Sea hub · Saudi Arabia · pilgrim + containers" },
    zones: [
      z("jed-approach", "Red Sea approach", "approach", [21.3, 38.95, 21.5, 39.15]),
      z("jed-port", "Jeddah terminals", "berth", [21.45, 39.1, 21.7, 39.4]),
    ],
  },
  {
    id: "salalah",
    name: "Salalah",
    country: "Oman",
    flag: "🇴🇲",
    region: "middle-east",
    nativeLocale: "ar",
    names: { ar: "صلالة", en: "Salalah", fr: "Salalah" },
    countryNames: { ar: "عمان", en: "Oman", fr: "Oman" },
    center: [16.95, 54.0],
    bbox: [16.85, 53.85, 17.1, 54.2],
    cargoStrength: ["container"],
    blurb: "Transshipment Océan Indien · Maersk hub",
    blurbs: { en: "Indian Ocean transshipment · Maersk hub" },
    zones: [
      z("slu-approach", "Approach", "approach", [16.85, 53.85, 16.95, 54.1]),
      z("slu-port", "Salalah port", "berth", [16.93, 53.95, 17.1, 54.15]),
    ],
  },

  // === Asia (extended) ===
  {
    id: "shanghai",
    name: "Shanghai / Yangshan",
    country: "China",
    flag: "🇨🇳",
    region: "asia",
    nativeLocale: "zh",
    names: {
      zh: "上海 / 洋山",
      en: "Shanghai / Yangshan",
      fr: "Shanghai / Yangshan",
      ja: "上海 / 洋山",
    },
    countryNames: { zh: "中国", en: "China", fr: "Chine", ja: "中国" },
    center: [30.6, 122.05],
    bbox: [30.45, 121.85, 30.75, 122.3],
    cargoStrength: ["container", "general-cargo"],
    blurb: "1er port conteneurs mondial · Yangshan deep-water",
    blurbs: { en: "World #1 container port · Yangshan deep-water" },
    zones: [
      z("sha-approach", "Yangshan approach", "approach", [
        30.45, 121.85, 30.6, 122.15,
      ]),
      z("sha-port", "Yangshan terminals", "berth", [30.55, 122.0, 30.75, 122.3]),
    ],
  },
  {
    id: "ningbo",
    name: "Ningbo-Zhoushan",
    country: "China",
    flag: "🇨🇳",
    region: "asia",
    nativeLocale: "zh",
    names: {
      zh: "宁波-舟山",
      en: "Ningbo-Zhoushan",
      fr: "Ningbo-Zhoushan",
      ja: "寧波-舟山",
    },
    countryNames: { zh: "中国", en: "China", fr: "Chine", ja: "中国" },
    center: [29.95, 121.85],
    bbox: [29.7, 121.5, 30.15, 122.4],
    cargoStrength: ["container", "dry-bulk", "crude"],
    blurb: "1er port mondial en tonnage · Zhoushan oil hub",
    blurbs: { en: "World #1 by tonnage · Zhoushan oil hub" },
    zones: [
      z("nbo-approach", "Hangzhou Bay", "approach", [29.7, 121.5, 29.95, 122.0]),
      z("nbo-port", "Ningbo terminals", "berth", [29.85, 121.7, 30.15, 122.4]),
    ],
  },
  {
    id: "shenzhen",
    name: "Shenzhen",
    country: "China",
    flag: "🇨🇳",
    region: "asia",
    nativeLocale: "zh",
    names: {
      zh: "深圳",
      en: "Shenzhen",
      fr: "Shenzhen",
      ja: "深圳",
    },
    countryNames: { zh: "中国", en: "China", fr: "Chine", ja: "中国" },
    center: [22.55, 114.0],
    bbox: [22.4, 113.8, 22.7, 114.3],
    cargoStrength: ["container"],
    blurb: "Conteneurs Sud-Chine · Yantian + Shekou",
    blurbs: { en: "South China container · Yantian + Shekou" },
    zones: [
      z("szx-approach", "Pearl River mouth", "approach", [22.4, 113.8, 22.55, 114.15]),
      z("szx-port", "Shenzhen terminals", "berth", [22.5, 113.95, 22.7, 114.3]),
    ],
  },
  {
    id: "hongKong",
    name: "Hong Kong",
    country: "Hong Kong",
    flag: "🇭🇰",
    region: "asia",
    nativeLocale: "zh",
    names: {
      zh: "香港",
      en: "Hong Kong",
      fr: "Hong Kong",
      ja: "香港",
    },
    countryNames: {
      zh: "香港",
      en: "Hong Kong",
      fr: "Hong Kong",
      ja: "香港",
    },
    center: [22.3, 114.15],
    bbox: [22.15, 113.95, 22.45, 114.4],
    cargoStrength: ["container"],
    blurb: "Hub conteneurs sud-Chine · Kwai Tsing terminals",
    blurbs: { en: "South China container hub · Kwai Tsing" },
    zones: [
      z("hkg-approach", "Approach", "approach", [22.15, 113.95, 22.3, 114.25]),
      z("hkg-port", "Kwai Tsing", "berth", [22.3, 114.1, 22.45, 114.3]),
    ],
  },
  {
    id: "busan",
    name: "Busan",
    country: "South Korea",
    flag: "🇰🇷",
    region: "asia",
    nativeLocale: "en",
    names: {
      en: "Busan",
      fr: "Busan",
      zh: "釜山",
      ja: "釜山",
    },
    countryNames: {
      en: "South Korea",
      fr: "Corée du Sud",
      zh: "韩国",
      ja: "韓国",
    },
    center: [35.1, 129.05],
    bbox: [34.95, 128.85, 35.2, 129.25],
    cargoStrength: ["container", "ro-ro"],
    blurb: "Transshipment Asie nord · Asie-USA gateway",
    blurbs: { en: "North Asia transshipment · Asia-USA gateway" },
    zones: [
      z("bus-approach", "Busan approach", "approach", [34.95, 128.9, 35.1, 129.2]),
      z("bus-port", "Busan terminals", "berth", [35.05, 128.95, 35.2, 129.2]),
    ],
  },
  {
    id: "yokohama",
    name: "Yokohama / Tokyo Bay",
    country: "Japan",
    flag: "🇯🇵",
    region: "asia",
    nativeLocale: "ja",
    names: {
      ja: "横浜 / 東京湾",
      en: "Yokohama / Tokyo Bay",
      fr: "Yokohama / Baie de Tokyo",
      zh: "横滨 / 东京湾",
    },
    countryNames: {
      ja: "日本",
      en: "Japan",
      fr: "Japon",
      zh: "日本",
    },
    center: [35.45, 139.65],
    bbox: [35.3, 139.5, 35.6, 139.9],
    cargoStrength: ["container", "lng", "ro-ro"],
    blurb: "Tokyo Bay · Yokohama + Chiba LNG · 1er pays importateur LNG",
    blurbs: {
      en: "Tokyo Bay · Yokohama + Chiba LNG · #1 LNG importer",
      ja: "東京湾 · 横浜 + 千葉 LNG · 世界最大 LNG 輸入国",
    },
    zones: [
      z("yok-approach", "Tokyo Bay approach", "approach", [
        35.3, 139.55, 35.45, 139.85,
      ]),
      z("yok-port", "Yokohama / Chiba", "berth", [35.4, 139.6, 35.6, 139.9]),
    ],
  },
  {
    id: "kaohsiung",
    name: "Kaohsiung",
    country: "Taiwan",
    flag: "🇹🇼",
    region: "asia",
    nativeLocale: "zh",
    names: {
      zh: "高雄",
      en: "Kaohsiung",
      fr: "Kaohsiung",
      ja: "高雄",
    },
    countryNames: { zh: "台湾", en: "Taiwan", fr: "Taïwan", ja: "台湾" },
    center: [22.6, 120.3],
    bbox: [22.45, 120.15, 22.75, 120.45],
    cargoStrength: ["container", "crude"],
    blurb: "Hub conteneurs Taiwan · Évergreen / Yang Ming",
    blurbs: { en: "Taiwan container hub · Evergreen / Yang Ming" },
    zones: [
      z("ksh-approach", "Approach", "approach", [22.45, 120.15, 22.6, 120.35]),
      z("ksh-port", "Kaohsiung port", "berth", [22.55, 120.25, 22.75, 120.45]),
    ],
  },
  {
    id: "portKlang",
    name: "Port Klang",
    country: "Malaysia",
    flag: "🇲🇾",
    region: "asia",
    nativeLocale: "en",
    names: { en: "Port Klang", fr: "Port Klang" },
    countryNames: { en: "Malaysia", fr: "Malaisie" },
    center: [3.0, 101.4],
    bbox: [2.85, 101.2, 3.15, 101.6],
    cargoStrength: ["container", "general-cargo"],
    blurb: "Détroit Malacca · transshipment Asie SE",
    blurbs: { en: "Strait of Malacca · SE Asia transshipment" },
    zones: [
      z("pkg-approach", "Strait approach", "approach", [2.85, 101.2, 3.0, 101.45]),
      z("pkg-port", "Port Klang terminals", "berth", [2.95, 101.3, 3.15, 101.55]),
    ],
  },
  {
    id: "colombo",
    name: "Colombo",
    country: "Sri Lanka",
    flag: "🇱🇰",
    region: "asia",
    nativeLocale: "en",
    names: { en: "Colombo", fr: "Colombo" },
    countryNames: { en: "Sri Lanka", fr: "Sri Lanka" },
    center: [6.95, 79.85],
    bbox: [6.8, 79.7, 7.1, 80.0],
    cargoStrength: ["container"],
    blurb: "Hub Océan Indien · transshipment Inde",
    blurbs: { en: "Indian Ocean hub · India transshipment" },
    zones: [
      z("cmb-approach", "Approach", "approach", [6.8, 79.7, 6.95, 79.9]),
      z("cmb-port", "Colombo port", "berth", [6.93, 79.8, 7.1, 79.95]),
    ],
  },
  {
    id: "nhavaSheva",
    name: "Nhava Sheva (Mumbai)",
    country: "India",
    flag: "🇮🇳",
    region: "asia",
    nativeLocale: "en",
    names: { en: "Nhava Sheva (Mumbai)", fr: "Nhava Sheva (Mumbai)" },
    countryNames: { en: "India", fr: "Inde" },
    center: [18.95, 72.95],
    bbox: [18.8, 72.75, 19.1, 73.15],
    cargoStrength: ["container", "general-cargo"],
    blurb: "1er port conteneurs Inde · JNPT",
    blurbs: { en: "India #1 container · JNPT" },
    zones: [
      z("nsa-approach", "Mumbai harbor", "approach", [18.8, 72.75, 18.95, 73.05]),
      z("nsa-port", "JNPT terminals", "berth", [18.9, 72.9, 19.1, 73.15]),
    ],
  },

  // === Africa ===
  {
    id: "durban",
    name: "Durban",
    country: "South Africa",
    flag: "🇿🇦",
    region: "africa",
    nativeLocale: "en",
    names: { en: "Durban", fr: "Durban" },
    countryNames: { en: "South Africa", fr: "Afrique du Sud" },
    center: [-29.87, 31.05],
    bbox: [-30.0, 30.85, -29.7, 31.25],
    cargoStrength: ["container", "dry-bulk", "crude"],
    blurb: "1er port d'Afrique · gateway Afrique australe",
    blurbs: { en: "Africa's #1 port · Southern Africa gateway" },
    zones: [
      z("dur-approach", "Durban approach", "approach", [-30.0, 30.95, -29.85, 31.2]),
      z("dur-port", "Durban port", "berth", [-29.9, 30.95, -29.75, 31.15]),
    ],
  },
  {
    id: "lagos",
    name: "Lagos / Apapa",
    country: "Nigeria",
    flag: "🇳🇬",
    region: "africa",
    nativeLocale: "en",
    names: { en: "Lagos / Apapa", fr: "Lagos / Apapa" },
    countryNames: { en: "Nigeria", fr: "Nigeria" },
    center: [6.43, 3.4],
    bbox: [6.3, 3.2, 6.55, 3.6],
    cargoStrength: ["container", "crude", "product"],
    blurb: "Nigeria oil exports · Tin Can / Apapa",
    blurbs: { en: "Nigeria oil exports · Tin Can / Apapa" },
    zones: [
      z("lag-approach", "Approach", "approach", [6.3, 3.25, 6.4, 3.5]),
      z("lag-port", "Lagos terminals", "berth", [6.4, 3.3, 6.55, 3.55]),
    ],
  },
  {
    id: "djibouti",
    name: "Djibouti",
    country: "Djibouti",
    flag: "🇩🇯",
    region: "africa",
    nativeLocale: "ar",
    names: { ar: "جيبوتي", en: "Djibouti", fr: "Djibouti" },
    countryNames: { ar: "جيبوتي", en: "Djibouti", fr: "Djibouti" },
    center: [11.6, 43.15],
    bbox: [11.45, 42.95, 11.8, 43.4],
    cargoStrength: ["container", "general-cargo"],
    blurb: "Bab el-Mandeb gateway · Doraleh terminal",
    blurbs: { en: "Bab el-Mandeb gateway · Doraleh terminal" },
    zones: [
      z("djb-approach", "Approach", "approach", [11.45, 42.95, 11.65, 43.2]),
      z("djb-port", "Djibouti / Doraleh", "berth", [11.55, 43.1, 11.8, 43.35]),
    ],
  },

  // === Chokepoints (extended) ===
  {
    id: "suez",
    name: "Suez Canal",
    country: "Chokepoint",
    flag: "⚓",
    region: "chokepoint",
    nativeLocale: "ar",
    names: {
      ar: "قناة السويس",
      en: "Suez Canal",
      fr: "Canal de Suez",
      de: "Suezkanal",
      es: "Canal de Suez",
      zh: "苏伊士运河",
      ja: "スエズ運河",
    },
    countryNames: {
      ar: "ممر استراتيجي",
      en: "Strategic chokepoint",
      fr: "Chokepoint stratégique",
    },
    center: [30.5, 32.35],
    bbox: [29.9, 32.2, 31.3, 32.55],
    cargoStrength: ["container", "crude", "product", "lng"],
    blurb:
      "Chokepoint stratégique · ~12% du commerce mondial · liaison Méd / Mer Rouge",
    blurbs: {
      en: "Strategic chokepoint · ~12% of global trade · Med/Red Sea link",
    },
    zones: [
      z("suez-north", "Mediterranean entry", "approach", [
        31.0, 32.2, 31.3, 32.5,
      ]),
      z("suez-canal", "Canal body", "channel", [29.95, 32.25, 31.0, 32.5]),
      z("suez-south", "Red Sea entry", "approach", [29.9, 32.4, 30.0, 32.55]),
    ],
  },
  {
    id: "malacca",
    name: "Strait of Malacca",
    country: "Chokepoint",
    flag: "⚓",
    region: "chokepoint",
    nativeLocale: "en",
    names: {
      en: "Strait of Malacca",
      fr: "Détroit de Malacca",
      de: "Straße von Malakka",
      es: "Estrecho de Malaca",
      zh: "马六甲海峡",
      ja: "マラッカ海峡",
      ar: "مضيق ملقا",
    },
    countryNames: {
      en: "Strategic chokepoint",
      fr: "Chokepoint stratégique",
      ar: "ممر استراتيجي",
    },
    center: [2.5, 101.5],
    bbox: [1.0, 99.5, 4.0, 103.5],
    cargoStrength: ["crude", "lng", "container", "product"],
    blurb:
      "Chokepoint Asie · ~30% du commerce maritime mondial · liaison Inde / Pacifique",
    blurbs: {
      en: "Asia chokepoint · ~30% of global maritime trade · India/Pacific link",
    },
    zones: [
      z("mlc-narrow", "Narrow passage", "channel", [1.5, 100.0, 3.5, 102.5]),
    ],
  },
];

export const PORTS_BY_ID: Record<string, Port> = Object.fromEntries(
  PORTS.map((p) => [p.id, p]),
);

export function getPort(id: string): Port | undefined {
  return PORTS_BY_ID[id];
}

export function findPortByPosition(lat: number, lon: number): Port | undefined {
  for (const p of PORTS) {
    const [s, w, n, e] = p.bbox;
    if (lat >= s && lat <= n && lon >= w && lon <= e) return p;
  }
  return undefined;
}

export function findZone(
  port: Port,
  lat: number,
  lon: number,
): Zone | undefined {
  for (const z of port.zones) {
    const [s, w, n, e] = z.bbox;
    if (lat >= s && lat <= n && lon >= w && lon <= e) return z;
  }
  return undefined;
}

export const DEFAULT_PORT_ID = "rotterdam";
